---
name: image-builder

on:
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go environment
        uses: red-hat-storage/ocs-osd-deployer@main
      - name: Run make test 5 times and store log files
        run: |
          for i in {1..5}
          do
            make test
            mv /tmp/ocs-osd-deployer.log /tmp/ocs-osd-deployer-$i.log;
          done
      - name: Build operator docker image
        run: make docker-build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: envtest-logs
          path: /tmp/ocs-osd-deployer*.log
          retention-days: 5
